### ISSUE TITLE
columns duplicated in first row

### ISSUE THREAD

**Issue by missinglink** [ggotti/g-naf-full-sqlite#3]
Heya,

I downloaded your docker image and noticed that (at least for the `LOCALITY_POINT` table) the columns are duplicated as the first row of the table.

```bash
sqlite> select rowid, * from LOCALITY_POINT limit 2;
rowid|locality_point_pid|date_created|date_retired|locality_pid|planimetric_accuracy|longitude|latitude
1|LOCALITY_POINT_PID|DATE_CREATED|DATE_RETIRED|LOCALITY_PID|PLANIMETRIC_ACCURACY|LONGITUDE|LATITUDE
2|500224299|2019-08-03||500224299||127.517389|-28.350204
```

**Comment by ggotti** [comment]
I've updated the SQLite3 version, which supports skipping the first row of the CSV.

**Comment by missinglink** [comment]
Thanks @ggotti, I was inspired by your work to have a play around with GNAF & SQLite, ended up writing a blog post about it https://geocode.earth/blog/2021/exploring-gnaf-with-sqlite/ cheers 👍
